version: '2.0'

services:
  service:
    build: service
    command: npm start
    network_mode: "host"
    ports:
      - 3000:3000
  db:
    dns: 127.0.0.222
    image: mongo
    ports:
      - 27018:27017
